# Generated by Django 4.2.3 on 2023-12-13 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_faculty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faculty',
            name='fdept',
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='fimage',
        ),
    ]
