# Generated by Django 4.2.3 on 2023-12-13 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_appointment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='aemail',
            new_name='Email',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='aname',
            new_name='Name',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='facname',
            new_name='faculty',
        ),
    ]
