# Generated by Django 4.2.3 on 2023-12-13 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_rename_aemail_appointment_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='bookeddate',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='faculty',
        ),
        migrations.AddField(
            model_name='appointment',
            name='PhoneNo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
