# Generated by Django 4.2.3 on 2023-12-13 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_appointment_departmentt'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='Departmentt',
            new_name='Department',
        ),
    ]
