# Generated by Django 4.2.3 on 2023-12-13 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_rename_departmentt_appointment_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='Date',
            field=models.DateField(auto_now=True),
        ),
    ]
