# Generated by Django 4.2.3 on 2023-12-13 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_appointment_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='Date',
        ),
    ]
